"""empty message

Revision ID: 0ea3a17cb35e
Revises: 
Create Date: 2021-10-13 23:45:14.833375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea3a17cb35e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schoolyear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('picture', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gender_id', sa.Enum('MALE', 'FEMALE', 'OTHER', name='enumgender'), nullable=True),
    sa.Column('gender_other', sa.String(length=128), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('mobile2', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gender_id', sa.Enum('MALE', 'FEMALE', 'OTHER', name='enumgender'), nullable=True),
    sa.Column('gender_other', sa.String(length=128), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('mobile2', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=218), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('teacher_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('status_class_id', sa.Enum('ACTIVE', 'FINISHED', 'CANCELLED', name='enumstatusclass'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyear.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students_class_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('students_class_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['students_class_id'], ['students_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_class_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_class_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'PORTUGUESE', 'HISTORY', 'GEOGRAPHY', 'ENGLISH', 'TECHNICAL_DRAWING', 'PHYSICAL_EDUCATION', 'BIOLOGY', 'PHYSICS', 'CHEMISTRY', 'SPANISH', 'SCIENCES', 'ARTS', name='enumsubjects'), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_class_id'], ['students_class.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classes_subjects_teachers_id', sa.Integer(), nullable=False),
    sa.Column('bimester', sa.Enum('first', 'second', 'third', 'fourth', 'final', 'recuperation', name='enumbimester'), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classes_subjects_teachers_id'], ['students_class_teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    op.drop_table('students_class_teachers')
    op.drop_table('students_class_students')
    op.drop_table('students_class')
    op.drop_table('presence')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('schoolyear')
    # ### end Alembic commands ###
