"""added user level

Revision ID: 8dbc09adc424
Revises: b57208612fff
Create Date: 2021-09-19 16:31:07.350726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbc09adc424'
down_revision = 'b57208612fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_level')
    # ### end Alembic commands ###
